#include "types.h"
#include "param.h"
#include "memlayout.h"
#include "aarch64.h"
#include "defs.h"
#include "device.h"

volatile static int started = 0;
extern char end[];  // first address after kernel loaded from ELF file

void _entry(void);
extern const char kernel_build_time[];   // generated by the Makefile at link
extern const char kernel_build_rev[];
void delay(uint32 c);
void boot_uart_mark(int c);

static void
start_secondary_cpus(void)
{
  // The standard Raspberry Pi AArch64 armstub parks CPU1..3 on spin-table
  // slots 0xe0, 0xe8 and 0xf0.  A custom armstub may already have sent them
  // to _entry; publishing these slots is harmless in that case.
  volatile uint64 *spin = (volatile uint64*)P2V(0xe0);
  uint64 entry = V2P((uint64)_entry);
  for(int cpu = 1; cpu < NCPU; cpu++){
    spin[cpu - 1] = entry;
    asm volatile("dc cvac, %0" :: "r"(&spin[cpu - 1]) : "memory");
  }
  asm volatile("dsb sy\n\tsev" ::: "memory");
}

// start() jumps here in EL1 on all CPUs.
void
main()
{
  boot_uart_mark('0');
  if(cpuid() == 0){
    // QEMU's Pi firmware parks secondary cores. This first port runs core 0.
    // kinit2() hands out RAM from EARLYTOP upward: the kernel image and its
    // BSS must end below it, or the allocator would reuse kernel memory.
    // printf is not ready yet, so report through the early boot UART.
    if(V2P(end) > EARLYTOP){
      for(char *m = "\nkernel image extends past EARLYTOP\n"; *m; m++)
        boot_uart_mark(*m);
      for(;;)
        asm volatile("wfe");
    }
    kinit1(end, P2V(EARLYTOP));  // memory covered by the bootstrap map
    boot_uart_mark('1');
    kvminit();       // create kernel page table
    boot_uart_mark('2');
    kvminithart();   // turn on paging
    boot_uart_mark('3');
    kinit2(P2V(EARLYTOP), P2V(PHYSTOP));
    boot_uart_mark('4');
    device_init();
    sdio_bus_init();
    usb_bus_init();
    consoleinit();
    ttyinit();
    printfinit();
    printf("\n");
    printf("xv6 kernel is booting\n");
    printf("build: bcm43430-sdio-v2\n");
    printf("kernel image built: %s (%s)\n", kernel_build_time, kernel_build_rev);
    printf("\n");
    procinit();      // process table
    workqueue_init(); // schedulable bottom halves run on kworker
    rnginit();       // BCM2837 hardware random source for cryptographic keys
    syncinit();      // process synchronization objects
    netinit();       // Ethernet/IPv4/UDP stack (loopback until NIC attaches)
    input_init();    // input core and /dev/input/event0 evdev bridge
    usbkbd_driver_init(); // bind USB HID boot keyboards during enumeration
    dwc2_driver_init();   // register/probe DWC2 USB host controller
    trapinit();      // trap vectors
    trapinithart();  // install trap vector
    gicv3init();     // set up interrupt controller
    gicv3inithart();
    timerinit();
    binit();         // buffer cache
    iinit();         // inode table
    fileinit();      // file table
    sd_driver_init(); // BCM SDHOST owns the external SD memory card
    arasan_sdio_driver_init(); // Arasan owns BCM43430/43455 on GPIO34--39
    fat32init();      // locate FS.IMG in a FAT32 boot partition
    brcmfmac_driver_init(); // firmware source is available after FAT32 init
    mt7601u_driver_init(); // bind enumerated USB MT7601U after firmware source
    ov5647_init();    // register camera sensor drivers (camsensor.h) ...
    camera_init();    // ... then the Unicam bridge probes them -> /dev/video0
    ext2init();       // optional read-only Linux ext2 partition
    vfsinit();        // mount non-native filesystems behind vnode operations
    userinit();      // first user process
    start_secondary_cpus();
    // kvmdump();    // enable to show the final kernel page table before init/sh
    __sync_synchronize();
    started = 1;
  } else {
    while(started == 0)
      ;
    __sync_synchronize();
    kvminithart();    // turn on paging
    printf("hart %d starting\n", cpuid());
    trapinithart();   // install trap vector
    gicv3inithart();
    timerinit();
  }

  scheduler();
}
