// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_ps     22
#define SYS_ext2read 23
#define SYS_ext2readdir 24
#define SYS_sync_create 25
#define SYS_sync_wait   26
#define SYS_sync_signal 27
#define SYS_sync_reset  28
#define SYS_sync_atomic 29
#define SYS_sync_destroy 30
#define SYS_udp_bind     31
#define SYS_udp_unbind   32
#define SYS_udp_send     33
#define SYS_udp_recv     34
#define SYS_icmp_send    35
#define SYS_icmp_recv    36
#define SYS_mount        37
#define SYS_tty_attach   38
#define SYS_vmdump       39
#define SYS_wifi_connect 40
#define SYS_net_dhcp     41
#define SYS_tcp_listen   42
#define SYS_tcp_accept   43
#define SYS_tcp_read     44
#define SYS_tcp_write    45
#define SYS_tcp_close    46
#define SYS_socket_listen 47
#define SYS_socket_accept 48
#define SYS_epoll_create 49
#define SYS_epoll_ctl    50
#define SYS_epoll_wait   51
#define SYS_fcntl        52
#define SYS_pty_open     53
#define SYS_getrandom    54
#define SYS_rename       55
#define SYS_udp_tryrecv  56
#define SYS_tty_set_foreground 57
#define SYS_udp_recv_timeout 58
#define SYS_sched_setscheduler 59
#define SYS_sched_getinfo 60
#define SYS_setnice      61
#define SYS_sched_setaffinity 62
#define SYS_sched_yield  63
#define SYS_clock_us     64
#define SYS_getcpu       65
#define SYS_clone        66
#define SYS_texit        67
#define SYS_tjoin        68
#define SYS_gettid       69
#define SYS_socket       70
#define SYS_bind         71
#define SYS_listen       72
#define SYS_lseek        73
#define SYS_fsync        74
#define SYS_fdatasync    75
#define SYS_ftruncate    76
#define SYS_pread        77
#define SYS_pwrite       78
