#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "// generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    my $sysname = shift // $name;
    print ".global $name\n";
    print "${name}:\n";
    print " mov x7, #SYS_${sysname}\n";
    print " svc #0\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep_ticks", "sleep");
entry("uptime");
entry("ps");
entry("ext2read");
entry("ext2readdir");
entry("sync_create");
entry("sync_wait");
entry("sync_signal");
entry("sync_reset");
entry("sync_atomic");
entry("sync_destroy");
entry("udp_bind");
entry("udp_unbind");
entry("udp_send");
entry("udp_recv");
entry("udp_tryrecv");
entry("udp_recv_timeout");
entry("icmp_send");
entry("icmp_recv");
entry("mount");
entry("tty_attach");
entry("tty_set_foreground");
entry("vmdump");
entry("wifi_connect");
entry("net_dhcp");
entry("tcp_listen");
entry("tcp_accept");
entry("tcp_read");
entry("tcp_write");
entry("tcp_close");
entry("socket_listen");
entry("socket_accept");
entry("epoll_create");
entry("epoll_ctl");
entry("epoll_wait");
entry("fcntl");
entry("pty_open");
entry("getrandom");
entry("rename");
entry("sched_setscheduler");
entry("sched_getinfo");
entry("setnice");
entry("sched_setaffinity");
entry("sched_yield");
entry("clock_us");
entry("getcpu");
entry("clone");
entry("texit");
entry("tjoin");
entry("gettid");
entry("socket");
entry("bind");
entry("listen");
entry("lseek");
