#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "// generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " mov x7, #SYS_${name}\n";
    print " svc #0\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("ps");
entry("ext2read");
entry("ext2readdir");
entry("sync_create");
entry("sync_wait");
entry("sync_signal");
entry("sync_reset");
entry("sync_atomic");
entry("sync_destroy");
entry("udp_bind");
entry("udp_unbind");
entry("udp_send");
entry("udp_recv");
entry("icmp_send");
entry("icmp_recv");
entry("mount");
entry("tty_attach");
entry("vmdump");
